version: 2

sources:
  - name: raw

    tables:
      - name: raw_hosts
        description: "This table contains hosts information"
        columns: 
          - name: id
            tests:
              - unique
              - not_null

      - name: raw_listings
      - name: raw_reviews
      - name: customers 
        description: "Contains information about customer orders."
      - name: orders
      - name: employees
      - name: users
